# Generated by Django 5.2 on 2025-07-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverySystem', '0002_alter_vehicle_options_remove_vehicle_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='mission_completed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
